name: "Git Mirror Action"
description: "Mirrors a git repository to a specified GitHub repository"

inputs:
  'source-repo-url':
    description: "URL of the source git repository"
    required: true
  'target-github-repo':
    description: "Target GitHub repository as `<owner>/<repo>` or just `<repo>`"
    required: true
  'target-ssh-key':
    description: "Private SSH deploy key for the target repository"
    required: false
  'target-token':
    description: "GitHub Token with contents:write permission for the target repository"
    required: false

outputs:
  'source-repo-url':
    description: "URL of the source git repository"
  'target-github-repo':
    description: "Full target repo name/path."
  'last-commit-hash':
    description: "Hash of the last mirrored commit"

runs:
  using: 'node20'
  main: 'index.js'
