name: "Reusable Git Mirror Workflow"

on:
  workflow_call:
    inputs:
      'source-repo':
        required: true
        type: string
      'target-repo':
        required: true
        type: string
    secrets:
      'SOURCE_SSH_KEY':
        required: false
      'TARGET_SSH_KEY':
        required: false
      'TARGET_TOKEN':
        required: false

jobs:
  'mirror-repository':
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: 'actions/checkout@main'

      - uses: './.github/actions/git-mirror'
        with:
          'source-repo':    ${{ inputs['source-repo']     }}
          'target-repo':    ${{ inputs['target-repo']     }}
          'source-ssh-key': ${{ secrets['SOURCE_SSH_KEY'] }}
          'target-ssh-key': ${{ secrets['TARGET_SSH_KEY'] }}
          'target-token':   ${{ secrets['TARGET_TOKEN']   }}

      - name: Log mirroring results
        run: |
          echo "Source repo path:  ${{ steps['mirror'].outputs['source-repo-path']  }}"
          echo "Target repo path:  ${{ steps['mirror'].outputs['target-repo-path']  }}"
          echo "Mirrored branches: ${{ steps['mirror'].outputs['mirrored-branches'] }}"
          echo "Last commit hash:  ${{ steps['mirror'].outputs['last-commit-hash']  }}"
