name: "Git Mirrors #1"

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  'mirror':
    strategy:
      matrix:
        'json':
          - |
            {
              "name": "beautifulsoup"
            }

    name: "Mirror `${{ fromJSON(matrix['json'])['name'] }}`"
  
    environment:
      name: "mirror--${{ fromJSON(matrix['json'])['name'] }}"
      url: "https://github.com/facsimiles/${{ fromJSON(matrix['json'])['name'] }}"

    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@main'
      - uses: './.github/actions/git-mirror'
        with:
          'source-repo':    ${{ vars['source-repo'] }}
          'target-repo':    ${{ vars['target-repo'] }}
          'target-ssh-key': ${{ secrets['TARGET_SSH_KEY'] }}
