name: "Git Mirrors #1"

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  'mirror':
    strategy:
      max-parallel: 1
      matrix:
        'json':
          - |
            {
              "name": "beautifulsoup"
            }

    name: "Mirror `${{ fromJSON(matrix['json'])['name'] }}`"
  
    environment:
      name: "mirror--${{ fromJSON(matrix['json'])['name'] }}"
      url: "https://github.com/facsimiles/${{ fromJSON(matrix['json'])['name'] }}"

    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@main'
      - id: 'mirror'
        uses: './.github/actions/git-mirror'
        with:
          'source-repo':    ${{ vars['SOURCE_REPO'] }}
          'target-repo':    ${{ vars['TARGET_REPO'] }}
          'target-ssh-key': ${{ secrets['TARGET_SSH_KEY'] }}

      - name: "Log mirroring results"
        run: |
          echo "Source repo path:  ${{ steps['mirror'].outputs['source-repo-path']  }}"
          echo "Target repo path:  ${{ steps['mirror'].outputs['target-repo-path']  }}"
          echo "Mirrored branches: ${{ steps['mirror'].outputs['mirrored-branches'] }}"
          echo "Last commit hash:  ${{ steps['mirror'].outputs['last-commit-hash']  }}"
