name: "Git Mirrors #1"

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  'mirror-beatifulsoup':
    environment: 'mirror--beautifulsoup'
    uses: './.github/workflows/.git-mirror.yml'
    with:
      'source-repo': 'https://git.launchpad.net/beautifulsoup'
      'target-repo': 'git@github.com:facsimiles/beautifulsoup.git'
    secrets:
      'TARGET_SSH_KEY': ${{ secrets['TARGET_SSH_KEY'] }}
