name: "Git Mirrors"

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  'mirror':
    continue-on-error: true
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        'json':
          - |
            {
              "name": "beautifulsoup"
            }

    name: "Mirror `${{ fromJSON(matrix['json'])['name'] }}`"
  
    environment:
      name: "${{ format('mirror--{0}', fromJSON(matrix['json'])['name']) }}"
      url:  >
        ${{ format('https://github.com/{0}/{1}',
              github.repository_owner,
              fromJSON(matrix['json'])['name']
        )}}

    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@main'
      - id: 'mirror'
        uses: './.github/actions/git-mirror'
        with:
          'source-repo':    ${{ vars['SOURCE_REPO'] }}
          'target-repo':    ${{ vars['TARGET_REPO'] }}
          'branch':         ${{ vars['BRANCH'] }}
          'source-ssh-key': ${{ secrets['SOURCE_SSH_KEY'] }}
          'target-ssh-key': ${{ secrets['TARGET_SSH_KEY'] }}
          'target-token':   ${{ secrets['TARGET_TOKEN'] }}

      - name: "Log mirroring results"
        run: |
          echo "Source repo path:  ${{ steps['mirror'].outputs['source-repo-path']  }}"
          echo "Target repo path:  ${{ steps['mirror'].outputs['target-repo-path']  }}"
          echo "Mirrored branches: ${{ steps['mirror'].outputs['mirrored-branches'] }}"
          echo "Last commit hash:  ${{ steps['mirror'].outputs['last-commit-hash']  }}"
